safe : false

server : true
auto : true

base-url : /
source : .
destination : ./_site
plugins : ./_plugins

pygments : true
markdown : maruku
permalink : /blog/:year/:month/:day/:title


# My own config

# sass:
syntax: scss        # scss|sass
style:  compressed  # nested|expanded|compact|compressed

asset_version: 1

css_root: /css
css:
- mav.css
- pygments.css
- fontello.css
#- disqus.css

exclude:
- README.md
- CNAME
- .gitignore
