safe : true

base-url : /
source : .
destination : ./_site
plugins : ./_plugins

pygments : true
markdown : maruku
permalink : /blog/:year/:month/:day/:title


# My own config

asset_version: 1

css_root: /css

css:

- mav.css

exclude:
- README.md
- CNAME
- .gitignore
